### ISSUE TITLE
Checking if Log Exists on boot always fails, but only visually

### ISSUE THREAD

**Issue by JamesR-cB** [MossTeK/AHK-Convertify#5]
Log checking on boot will claim it's always generating a new log file every single time the application is launched. I believe this is related to how my log file is generated and checked - if I was to guess, I think AHK is treating the input "literally" and not resolving variables.

![image](https://user-images.githubusercontent.com/5680448/183480482-6df6b740-1e2c-4d76-b330-00afb36ca83c.png)

In other words, I think it is literally looking for the file "log-%appVersion%-%buildNumber%.txt" on disk, which of course doesn't exist as the variables appVersion and buildNumber are instead resolved to the variable's current assignment. 

However, all log output is still correctly redirected to the right file, so the only downside is each log file will report the log file was missing and it generated a new one, even if it wasn't missing and didn't generate a new one at all.

This one is very minor and fixing it would remove the automatic version incrementation and build number logic I built, which isn't a huge deal but I'd rather fix the core problem and not the symptoms, and honestly may not be worth fixing at all.

**Comment by JamesR-cB** [comment]
Note: This isn't a simple variables-declared-out-of-ourder problem either, as the version info is declared on lines 50 and 51, whereas doesLogLifeExist is called on line 66.

**Comment by MossTeK** [comment]
The issue is in the variable being called within the FileExsist function. The strings won't enumerate while being called. we can concatenate those variables to a separate variable in the doesLogFileExsist() function and call that variable in the function instead. I believe the issue is an AHK issue, this was the only way I was able to get it working.

Here is the new function

doesLogFileExist(){
logFileName = %A_ScriptDir%/log-%appVersion%-%buildNUmber%.txt ; The string wont enumerate when called in the FileExsists funciton so we have to declare the filepath as a vairiable. This is the only way I could get this working I suspect this is an AHK issue.
	if FileExist(logFileName){
	logAddInfo("I/O - Log file exists!")
	return
	}

	if !FileExist(logFileName){
	logAddError("I/O - Log file does not exist, creating new log.")
	return
	}

}
